version: "3"

services:
  item-service-v2:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redisv2

  redisv2:
    image: redis
    ports:
      - 6379
    volumes:
      - redisv2:/data

volumes:
  redisv2:
